import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistry";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" data-color-scheme="light">
      <body className="antialiased">
        <ThemeRegistry>
          {children}  
        </ThemeRegistry> 
      </body>
    </html>
  );
}
