import { Inter } from "next/font/google";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { Button, Typography } from "@mui/joy";

import styles from './layout.module.css'

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={styles.layoutContainer}>
      <nav className="flex justify-between">
        <div className="flex items-center gap-2">
          <img src="/profile.png" height={'70px'} alt="" />
          <div>
            <Typography level="title-md">Marcelo da Silva</Typography>
            <Typography level="body">Apartmento 01-B</Typography>
          </div>
        </div>
        <Button variant="outlined" endDecorator={"+"}>Sair</Button>
      </nav>
      {children}
    </div>
  );
}
