import { Button, Typography } from "@mui/joy";

import styles from './layout.module.css'
import Image from "next/image";
import { Logout } from "@mui/icons-material";
import Link from "next/link";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <div className={styles.layoutContainer}>
      <nav className="flex justify-between">
        <div className="flex items-center gap-5">
          <Image className={"rounded-full"} src="/profile.png" height={'70'} width={"70"} alt="" />
          <div>
            <Typography level="title-md">Marcelo da Silva</Typography>
            <Typography level="body-md">Apartmento 01-B</Typography>
          </div>
        </div>
        <div className={"flex items-center"}>
           <Link href={'/'}><Button variant="outlined" color="neutral" endDecorator={<Logout/>}>Sair</Button></Link>
        </div>
      </nav>
      {modal}
      {children}
    </div>
  );
}
